version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:202007-01'
    steps:
      - checkout
      - run: curl --version
      - run: ls -l
      - run: sh create_local_db.sh
      - run: npm install
      - run: npm run-script seed
      - run: npm test
